# Generated by Django 2.0.3 on 2018-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon_ab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BayesianABTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=50)),
                ('experiment_person', models.CharField(default='sanjeev', max_length=50)),
                ('experiment_type', models.CharField(max_length=50)),
                ('control', models.CharField(max_length=50)),
                ('hypothesis', models.CharField(max_length=50)),
                ('control_sample_size', models.IntegerField(blank=True, null=True)),
                ('hypothesis_sample_size', models.IntegerField(blank=True, null=True)),
                ('control_conversion_rate', models.FloatField(blank=True, null=True)),
                ('hypothesis_conversion_rate', models.FloatField(blank=True, null=True)),
                ('analysis_type', models.CharField(default='analytic', max_length=50)),
                ('decision_variable', models.CharField(default='lift', max_length=50)),
                ('decision_rule', models.CharField(default='rope', max_length=50)),
                ('decision_alpha', models.FloatField(default=0.95)),
                ('slug', models.SlugField(default='test-slug', max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='ABTest',
        ),
    ]
